---
title: "MultiAssayExperiment: Quick Start Guide"
author: "Marcel Ramos"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Quick-start Guide}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    number_sections: yes
    toc: yes
---

```{r, echo=FALSE, warning=FALSE}
suppressPackageStartupMessages({
    library(MultiAssayExperiment)
    library(S4Vectors)
    })
```

# Key Features of the MultiAssayExperiment API

## pData - biological units

```{r}
pheno <- DataFrame(id = 1:4, type = c("a", "a", "b", "b"),
                   sex = c("M", "F", "M", "F"),
                   row.names = c("Bob", "Sandy", "Jake", "Lauren"))
```

## ExperimentList - experiment data

```{r}
dataset1 <- matrix(rnorm(20, 5, 1), ncol = 5,
                  dimnames = list(paste0("GENE", 4:1),
                                  paste0("sample", LETTERS[1:5])))
dataset2 <- matrix(rnorm(12, 3, 2), ncol = 3,
                   dimnames = list(paste0("ENST0000", 1:4),
                                   paste0("samp", letters[1:3])))

expList <- list(exp1 = dataset1, exp2 = dataset2)
expList
```

## sampleMap - relationship graph

```{r}
map1 <- DataFrame(primary = c("Bob", "Jake", "Sandy", "Sandy", "Lauren"),
                  colname = paste0("sample", LETTERS[1:5]))
map2 <- DataFrame(primary = c("Jake", "Sandy", "Lauren"),
                  colname = paste0("samp", letters[1:3]))
sampMap <- listToMap(list(exp1 = map1, exp2 = map2))
sampMap
```


## MultiAssayExperiment - infrastructure class

```{r}
MultiAssayExperiment(expList, pheno, sampMap)
```

